name: panels_system
description: "Pane and tabs system for flutter"
version: 0.1.0
homepage: https://github.com/ronw98/flutter_pane_system
repository: https://github.com/ronw98/flutter_pane_system
issue_tracker: https://github.com/ronw98/flutter_pane_system/issues

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_resizable_container: ^3.0.0
  gap: ^3.0.1
  intersperse: ^2.0.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
